### ISSUE TITLE
Please finish up to be absorbed upstream

### ISSUE THREAD

**Issue by yarikoptic** [Vifon/ncdu-annex#1]
I love ncdu and git-annex. Just by incident found your repository (thanks to GitHub keywords). Sounds great and what I often need. I wondered if you tried to get your changes merged upstream?

**Comment by vifon** [comment]
No I didn't. I don't consider my patches robust enough to warrant merging them upstream. Let's say that I could support [80% of cases with 20% of effort while the remaining 20% would require 80% of my effort](https://en.wikipedia.org/wiki/Pareto_principle). Even if I would make it more robust, it seems too niche to make the upstream support it.

Personally I have both `ncdu` and `ncdu-annex` installed independently under different names (as I suggested in the readme).

**Comment by jangondol** [comment]
@yarikoptic and anyone else who found this thorugh web search: upstream `ncdu` now has [native support](https://code.blicky.net/yorhel/ncdu/issues/14) for this: `ncdu -L`. And there's also this workaround for exploring the size of symlinked files: `du -akL mydirectory | xdiskusage -aq` (it has the advantage of displaying the depth of several directories at once).

**Comment by yarikoptic** [comment]
`ncdu -L` indeed helps!  but it double counts (would show size for both the symlink and .git/annex'ed original location), unlike the initial idea here: "Automatically ignore (--exclude) the ".git/annex" directory with the actual files," .  I guess `ncdu -L` is the best generic approach, and only some "git-annex-aware" solution like this could provide such functionality (unless making `ncdu` git-annex aware which I would not mind at all but it might be too custom)

**Comment by vifon** [comment]
I'm closing the issue but feel free to continue the discussion as needed. Good to know `ncdu` now supports `-L`, even with the issues @yarikoptic mentioned, thanks for pointing it out!
